### ISSUE TITLE
SynapsesParams tab in Simulator Configuration window does not populate

### ISSUE THREAD

**Issue by jConquest** [UWB-Biocomputing/WorkBench#39]
Tested with all possible simulator configurations. Regardless of settings, SynapsesParams tab is never populated

**Comment by stiber** [comment]
This is expected. Right now, synapse parameters are hard coded into the simulator, so there are no parameters. But, eventually, this will get fixed.

**Comment by stevecl5** [comment]
Regardless of the status of `SynapsesParams` in particular, Workbench should be robust enough to handle an empty params class. The real question is: How should an empty params class be handled by the input configuration dialog?

Currently, the `DynamicInputConfigurationDialog` creates a tab for each of the `ModelParams`. Since `SynapsesParams` exists but is empty, a tab is created but there are no input fields.

Some options for handling the empty params class:
1. No change. A tab is created but left blank. (not recommended)
2. A tab is created with an informative message such as "No inputs to configure."
3. No tab is created 

@stiber What do you think  would make the most sense from a user perspective?

**Comment by stiber** [comment]
> 1. No change. A tab is created but left blank. (not recommended)
> 2. A tab is created with an informative message such as "No inputs to configure."
> 3. No tab is created

I guess number 2, with "No parameters to configure."

**Comment by stevecl5** [comment]
![image](https://user-images.githubusercontent.com/19354643/133894148-81eae083-652f-4c31-9112-f0220ad239d8.png)

Implemented in PR #97
