### ISSUE TITLE
Script output files are not copied to project folder when running simulation locally

### ISSUE THREAD

**Issue by king-shak** [UWB-Biocomputing/WorkBench#83]
While you can pull, build, and run a simulation locally, once it's finished and you press the "Analyze" button in the Simulation Runtime Environment (SRE) dialog, it fails to copy the scriptStatus file. As a result, no provenance is generated for it.

It creates the scriptStatus file directly in my user directory, yet it seems it's trying to grab it from the directory Workbench is being run from.

Here's the full stack trace:
![terminal error](https://user-images.githubusercontent.com/12002831/124217373-16b39f80-daad-11eb-9cac-ff4230adfc4d.png)

Here is the error from the SRE (right after "Gathering simulation provenance..." towards the bottom):
![SRE error](https://user-images.githubusercontent.com/12002831/124217466-3f3b9980-daad-11eb-9348-8cc30a7fae17.png)

And here is what the project directory tree looks like:
![project directory tree](https://user-images.githubusercontent.com/12002831/124217535-5f6b5880-daad-11eb-92ce-e049049edf68.png)

**Comment by stevecl5** [comment]
The source of this problem is that the script output are created in two different places when running local simulations. Specifically, `simStatus.txt` and `SHA1Key.txt` are created in the user's working directory, and `scriptStatus.txt` and `output.txt` are created in the user's home directory. The Workbench operation fails because it is looking for `scriptStatus.txt` in the user's working directory (causing everything after that point to fail as well).

The direct fix is to have workbench check the home directory for the script status file since that is where it exists. However, it would be better to have all of these files be created in the same location. Additionally, I discovered the home directory `~/` is hardcoded in the script generation code which is shared for both remote and local simulations, making it somewhat more difficult to change.

Before making any big changes, we need to first decide where we want the script output files to be created. For now, I fixed the specific issue of Workbench not being able to find `scriptStatus.txt`. However, the larger issue of how we want to manage these files is still unresolved.

**Comment by stiber** [comment]
Since we're discussing a bunch of "artifact organization" issues, and will want to go over the typical investigator workflow, I suggest that we catalog all of the artifacts (files) that Workbench interacts with, as things like internal templates (only one ever exists), group of experiments level (one for multiple simulations), and per-simulation (including both Workbench and Graphitti/BrainGrid). It seems like there may be duplicates. We can use this to help us think through these organizational issues.
